### ISSUE TITLE
Add a "Run" stage in the pipeline

### ISSUE THREAD

**Issue by mjemnawaz** [fireant-bot/fireant#56]
Run "docker run ... " command in Jenkins. Include environment variable in a way that does not expose the private information.

**Comment by mjemnawaz** [comment]
docker run currently causes pipeline failure due to the following issue: 
```
+ docker run -e GITHUB_USERNAME=fireantci -e GITHUB_PASSWORD=ff1b89aa2356ab63cde86f3402c17cbae8071ae5 -e GITHUB_EMAIL=fireantbot@gmail.com -e REQUIRES_IO_TOKEN=930bdef13934eb6a069a596af84032f70422df33 fireantbot/fireant 

Traceback (most recent call last):
  File "/usr/src/app/./main.py", line 300, in <module>
    if setup_env():
  File "/usr/src/app/./main.py", line 62, in setup_env
    REPO_LINK = config.FORKED_LINK
AttributeError: module 'config' has no attribute 'FORKED_LINK'

```

**Comment by mjemnawaz** [comment]
docker run currently causes pipeline failure due to the following issue:
```
+ docker run -e GITHUB_USERNAME=XXXXX -e GITHUB_PASSWORD=XXXXX -e GITHUB_EMAIL=XXXXX -e REQUIRES_IO_TOKEN=XXXXX fireantbot/fireant 

Traceback (most recent call last):
  File "/usr/src/app/./main.py", line 300, in <module>
    if setup_env():
  File "/usr/src/app/./main.py", line 62, in setup_env
    REPO_LINK = config.FORKED_LINK
AttributeError: module 'config' has no attribute 'FORKED_LINK'
```
