### ISSUE TITLE
Jenkins Pipeline Run Error

### ISSUE THREAD

**Issue by mjemnawaz** [fireant-bot/fireant#65]
Fix incorrect syntax in the docker run command that caused the pipeline to fail.

**Comment by lewismc** [comment]
@mjemnawaz the [error persists](https://ci-builds.apache.org/job/Nutch/job/nutch-fireant/29/console)
```
Started by user Lewis John McGibbney
Obtained Jenkinsfile from git https://github.com/fireant-bot/fireant
Running in Durability level: PERFORMANCE_OPTIMIZED
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 29: Invalid trigger type "GenericTrigger". Valid trigger types: [upstream, cron, snapshotDependencies, githubPush, issueCommentTrigger, pollSCM] @ line 29, column 9.
           GenericTrigger(
           ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:571)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:523)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:337)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```
Can you please propose a fix? Thank you

**Comment by lewismc** [comment]
Also, can you please make sure the Jenkinsfile passes all of the syntax checks we performed previously.
